config/routes.rb
Rails.application.routes.draw do

  post 'order_complete' => 'cart#order_complete'

  post 'add_to_cart' => 'cart#add_to_cart'

  get 'view_order' => 'cart#view_order'

  post 'checkout' => 'cart#checkout'

  resources :orders

  resources :line_items

  devise_for :users
  
  root 'storefront#all_items'

  get 'categorical' => 'storefront#items_by_category'

  get 'branding' => 'storefront#items_by_brand'

  get 'all' => 'storefront#all_items'

  resources :categories

  resources :products

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :products
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
	belongs_to :product
	belongs_to :order
end

app/models/order.rb
class Order < ActiveRecord::Base
	has_many :line_items
	belongs_to :user

	serialize :order_item, Hash
end

app/models/product.rb
class Product < ActiveRecord::Base
	has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

	belongs_to :category
	has_many :line_items
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :orders
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :get_categories, :get_brands
  
  def get_categories
  	@categories = Category.all
  end

  def get_brands
  	@brands = Product.pluck(:brand).sort
  	@brands.uniq!
  end
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
	before_action :authenticate_user!, :except => [:add_to_cart, :view_order]

  def add_to_cart
  	line_item = LineItem.new
  	line_item.product_id = params[:product_id]
  	line_item.quantity = params[:quantity]
  	line_item.save

  	line_item.line_item_total = line_item.product.price * line_item.quantity
  	line_item.save

  	redirect_to root_path
  end

  def view_order
  	@line_items = LineItem.all
  end

  def checkout
  	@line_items = LineItem.all
  	@order = Order.new
  	@order.user_id = current_user.id

  	sum = 0

  	@line_items.each do |line_item|
  		@order.order_item[line_item.product_id] = line_item.quantity
  	end

  	@line_items.each do |line_item|
  		sum += line_item.line_item_total
  	end

  	@order.subtotal = sum
  	@order.sales_tax = sum * 0.07
  	@order.grand_total = sum + @order.sales_tax
  	@order.save

  	@line_items.each do |line_item|
  		line_item.product.quantity -= line_item.quantity
  		line_item.product.save
  	end

  	LineItem.destroy_all
  end

  def order_complete
    @order = Order.find(params[:order_id])
    @amount = (@order.grand_total.to_f.round(2) * 100).to_i

    customer = Stripe::Customer.create(
      :email => current_user.email,
      :card => params[:stripeToken]
    )

    Stripe::Charge.create(
      :customer => customer.id,
      :amount => @amount,
      :description => 'Rails Stripe Customer',
      :currency => 'usd'
    )
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :price, :quantity, :description, :rating, :category_id, :image, :brand)
    end
end

app/controllers/storefront_controller.rb
class StorefrontController < ApplicationController
	def all_items
		@products = Product.all
	end

	def items_by_brand
		@products = Product.where(brand: params[:brand])
		
	end

	def items_by_category
		@products = Product.where(category_id: params[:category_id])
		@category = Category.find(params[:category_id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/storefront_helper.rb
module StorefrontHelper
end

app/views/cart/add_to_cart.html.erb
<h1>Cart#add_to_cart</h1>
<p>Find me in app/views/cart/add_to_cart.html.erb</p>

app/views/cart/checkout.html.erb
<h1>Thanks for shopping with us!</h1>
<p>Let's review your order:</p>

<% @order.order_item.each do |product_id, quantity| %>
	<ul>
		<li><%= Product.find(product_id).name %> : <%= quantity %></li>
	</ul>
<% end %>

<p>
	<strong>Order Total:</strong> <%= number_to_currency @order.grand_total %>
</p>

<%= form_tag order_complete_path do %>
	<%= hidden_field_tag :order_id, @order.id %>
	<script
    src="https://checkout.stripe.com/checkout.js" class="stripe-button"
    data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
    data-amount="<%= @order.grand_total.to_f.round(2) * 100 %>"
    data-description="Order #: <%= @order.id %>">
  </script>
<% end %>

app/views/cart/order_complete.html.erb
<h2>Thank you for your order!</h2>

<h5>Order #: <%= @order.id %> will be shipping as soon as possible!</h5>

app/views/cart/view_order.html.erb
<h1>My Cart</h1>

<div>
	<% @line_items.each do |line_item| %>
		<ul>
			<li><%= line_item.product.name %></li>
			<li><%= number_to_currency line_item.product.price %></li>
			<li><%= line_item.quantity %></li>
			<li>Subtotal: <%= number_to_currency line_item.line_item_total %></li>
		</ul>
	<% end %>
</div>

<div>
	<%= link_to "Proceed to Checkout?", checkout_path, method: :post, class: "btn btn-success" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ecommerce</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<nav class="navbar navbar-default navbar-fixed-top">
		<div class="container-fluid">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
				</button>

				<%= link_to 'VAPELIFE', all_path, class: 'navbar-brand' %>
			</div>

			<ul class="nav navbar-nav">
				<li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Categories<span class="caret"></span></a>
          <ul class="dropdown-menu">
          	<% @categories.each do |category| %>
          	  <li><%= link_to category.name, categorical_path(category_id: category.id) %></li>
            <% end %>
          </ul>
        </li>

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Brands<span class="caret"></span></a>
          <ul class="dropdown-menu">
          	<% @brands.each do |brand| %>
          	  <li><%= link_to brand, branding_path(brand: brand) %></li>
            <% end %>
          </ul>
        </li>
			</ul>

			<div>
				<ul class="nav navbar-nav navbar-right">
					<% if user_signed_in? %>
						<p class="navbar-text">Logged in as <%= current_user.email %></p>
						<li><%= link_to 'My Cart', view_order_path %></li>
						<li><%= button_to 'Log Out', destroy_user_session_path, method: :delete, class: 'btn btn-default navbar-btn' %></li>
					<% else %>
						<li><%= button_to 'Sign Up', new_user_registration_path, method: :get , action: :new, class: 'btn btn-default navbar-btn' %></li>
						<li><%= button_to 'Log In', new_user_session_path, class: 'btn btn-default navbar-btn' %></li>
					<% end %>
				</ul>
			</div>
		</div>
	</nav>

	<p id="notice"><%= notice %></p>

	<div class="container">
		<%= yield %>
	</div>
</body>
</html>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br>
    <%= f.number_field :quantity %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :rating %><br>
    <%= f.number_field :rating %>
  </div>
  <div class="field">
    <%= f.label :category_id %><br>
    <%= f.collection_select :category_id, @categories, :id, :name %>
  </div>
  <div>
    <%= f.label :brand %><br>
    <%= f.text_field :brand %>
  </div>
  <div class="field">
    <%= f.file_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Products</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Brand</th>
      <th>Price</th>
      <th>Quantity</th>
      <th>Description</th>
      <th>Rating</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.brand %></td>
        <td><%= product.price %></td>
        <td><%= product.quantity %></td>
        <td><%= product.description %></td>
        <td><%= product.rating %></td>
        <td><%= product.category.name %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Brand:</strong>
  <%= @product.brand %>
</p>
<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @product.quantity %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @product.rating %>
</p>

<p>
  <strong>Category:</strong>
  <%= @product.category_id %>
</p>

<p>
  <strong>Image:</strong>
  <%= image_tag @product.image.url(:thumb) %>
</p>

<p>
  <%= form_tag('/add_to_cart') do %>
    <%= hidden_field_tag :product_id, @product.id %>
    <%= number_field_tag :quantity, nil, placeholder: "How many?" %><br><br>
    <%= submit_tag "Buy", class: "btn btn-success" %>
  <% end %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', all_path %>

app/views/storefront/_products.html.erb
<div class="row">
	<% @products.each_with_index do |product, n| %>
		<div class="col-md-4">
			<div class="well center-it">
				<%= image_tag product.image.url(:thumb) %>
				<h3><%= link_to product.name, product %></h3>
				<p><%= number_to_currency product.price %></p>
				<p>
					<a href="#" data-toggle="modal" data-target="#myModal_<%= product.id %>">
						<span class="glyphicon glyphicon-plus"> Info</span>
					</a>
				</p>
			</div>
		</div>

		<div class="modal fade" id="myModal_<%= product.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
		  <div class="modal-dialog" role="document">
		    <div class="modal-content">
		      <div class="modal-header">
		        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
		        <h4 class="modal-title" id="myModalLabel"><%= product.name %></h4>
		      </div>
		      <div class="modal-body">
		        <%= product.description %>
		      </div>
		      <div class="modal-footer">
		        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
		      </div>
		    </div>
		  </div>
		</div>
		<% if (n+1)%3 == 0 %>
			</div>
			<div class="row">
		<% end %>
	<% end %>
</div>

app/views/storefront/all_items.html.erb
<h1>DO YOU EVEN VAPE!?</h1>

<%= render 'products' %>

app/views/storefront/items_by_brand.html.erb
<h1></h1>

<%= render 'products' %>

app/views/storefront/items_by_category.html.erb
<h1>Showing <%= @category.name %></h1>

<%= render 'products' %>